#!/bin/bash

echo "🚀 Google Search Console Setup Guide"
echo "===================================="
echo ""

echo "✅ Google Cloud Project: govaiapp"
echo "✅ Search Console API: Enabled"
echo "✅ Service Account Created: custodiacompliance-api"
echo ""

echo "📋 Next Steps:"
echo ""
echo "1. For Search Console API, you need OAuth 2.0 credentials (not service account)"
echo ""
echo "2. Go to: https://console.cloud.google.com/apis/credentials?project=govaiapp"
echo ""
echo "3. Click 'Create Credentials' > 'OAuth client ID'"
echo ""
echo "4. Choose 'Desktop app' as application type"
echo ""
echo "5. Download the credentials JSON file"
echo ""
echo "6. Save it as 'credentials.json' in the project root"
echo ""
echo "7. Run: npx tsx scripts/get-search-console-token.ts"
echo ""
echo "Alternative (Easier):"
echo "Use the Google Search Console web interface to verify your site"
echo "Then use the search console web UI for tracking (it's free!)"
echo ""
echo "📊 The API integration is ready when you have OAuth credentials!"
echo "   Until then, the system will work with fallback data."
